name: Bug report
description: Report a reproducible problem in PathSafe.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        Please do not include real patient data or PHI.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A short, clear summary of the problem.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps that reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: PathSafe version
      placeholder: e.g. 1.0.2
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. Windows 11, macOS 14, Ubuntu 24.04
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python version (if relevant)
      placeholder: e.g. 3.11.9
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste logs or attach screenshots. Remove sensitive data first.
      render: shell
    validations:
      required: false

