name: Feature request
description: Suggest an improvement for PathSafe.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement.
        Please keep requests focused and concrete.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: Describe the current pain point.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should PathSafe do?
      placeholder: Describe the behavior you would like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other solutions you considered.
      placeholder: Optional
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Clinical, research, workflow, or technical context.
      placeholder: Optional
    validations:
      required: false

